### PR TITLE
Update to Spark 0.3.1

### PR DESCRIPTION
**Pull request by kn0wmad**

### CODE REVIEW

**Comment by chrisguida** [comment]
Blocked by https://github.com/Start9Labs/c-lightning-wrapper/pull/18

**Comment by kn0wmad** [comment]
Complete

**Comment by chrisguida** [comment]
This is the 0.3 version of spark, we need to update this too

**Comment by chrisguida** [comment]
Closed in favor of https://github.com/Start9Labs/spark-wallet-wrapper/pull/11

0.2.x PR was here: https://github.com/Start9Labs/spark-wallet-wrapper/pull/8

**Pull request closed without merging**
